name: 'Git Anti Virus Scan '
on:
  push:
    branches:
      - 'master'
jobs:
  gitavscan:
    runs-on: ubuntu-latest
    name: AV scan
    steps:
    - uses: actions/checkout@v2
    - name: Git AV Scan
      uses: djdefi/gitavscan@main
